// ParcelWs/trmrk-localfsapinotes-webapp/src/components/panel/Panel.tsx
import React, { useEffect, useRef } from "react";
import { useSelector, useDispatch } from 'react-redux'

import Box from "@mui/material/Box";
import { SxProps, Theme } from "@mui/material";

export default function Panel({
    children,
    isScrollable,
    className,
    style,
  }: {
    children: React.ReactNode,
    isScrollable: boolean,
    className?: string | null | undefined
    style?: SxProps<Theme> | null | undefined
  }) {
    return (<Box className={[ isScrollable ? "trmrk-scrollable" : null, className ?? null ].join(" ")} sx={style ?? {}}>
        { children }
      </Box>);
}

// ParcelWs/apps/trmrk-localfs-quicknotes-solidjs-tauriapp/src/trmrk-solidjs/components/AppLayout/Panel.tsx
import { ParentComponent } from "solid-js";

export interface PanelProps {
  cssClass?: string | null | undefined;
  isScrollable?: boolean | null | undefined;
}

const Panel: ParentComponent<PanelProps> = (props) => {
  return (<div class={["trmrk-panel", props.isScrollable ? "trmrk-scrollable overflow-scroll" : "", props.cssClass ?? ""].join(" ")}>
    {props.children}
  </div>);
}

export default Panel;
