// JsWs/libs/trmrk-react/src/lib/components/TrmrkUserMessage/TrmrkUserMessage.tsx
import React, { CSSProperties } from "react";
import { Icon } from "@iconify/react";

import { UserMessageLevel, NullOrUndef } from '@/src/trmrk/core';
import { Placement } from "@/src/trmrk-browser/core";

import { CommponentProps } from "../defs/common";
import TrmrkBtn from "../TrmrkBtn/TrmrkBtn";

import "./TrmrkUserMessage.scss";

export interface TrmrkUserMessageProps extends CommponentProps {
  msgLevel: UserMessageLevel;
  message: string;
  arrowPlacement: Placement;
  arrowStyle?: CSSProperties | NullOrUndef;
}

export default function TrmrkUserMessage(
  { cssClass, msgLevel, message, arrowPlacement = Placement.None, arrowStyle }: Readonly<TrmrkUserMessageProps>
) {
  const [messageFadeOut, setMessageFadeOut] = React.useState(false);

  const cssClassName = React.useMemo(() => {
    let cssClass: string;

    switch (msgLevel) {
      case UserMessageLevel.Success:
        cssClass = 'trmrk-success';
        break;
      case UserMessageLevel.Info:
        cssClass = 'trmrk-info';
        break;
      case UserMessageLevel.Warn:
        cssClass = 'trmrk-warn';
        break;
      case UserMessageLevel.Error:
        cssClass = 'trmrk-error';
        break;
      default:
        throw new Error(`Invalid user message level: ${msgLevel}`);
    }

    return cssClass;
  }, [msgLevel]);

  const arrowCssClass = React.useMemo(() => {
    let cssClass: string;

    switch (arrowPlacement) {
      case Placement.None:
        cssClass = '';
        break;
      case Placement.Top:
        cssClass = 'trmrk-placement-top';
        break;
      case Placement.Right:
        cssClass = 'trmrk-placement-right';
        break;
      case Placement.Bottom:
        cssClass = 'trmrk-placement-bottom';
        break;
      case Placement.Left:
        cssClass = 'trmrk-placement-left';
        break;
      default:
        cssClass = '';
        break;
    }

    return cssClass;
  }, [arrowPlacement]);

  return <div className={["trmrk-user-message-container", cssClass ?? ''].join(" ")}>
    <div className={['trmrk-user-message', cssClassName, messageFadeOut ? 'trmrk-fade' : ''].join(' ')}>
      <TrmrkBtn cssClass="trmrk-close-icon-btn"><Icon icon="mdi:close" /></TrmrkBtn>
      <div className="trmrk-content">
        <div className="trmrk-content-text trmrk-wrap-content">
          <span className="trmrk-text-part">{ message }</span>
        </div>
      </div>
      { arrowCssClass && <svg className="trmrk-arrow arrowCssClass" viewBox="0 0 20 10" style={ arrowStyle ?? undefined }>
        <path className="trmrk-arrow-body" strokeWidth="1" d="M 0 10 L 10 0 L 20 10" />
        <path className="trmrk-arrow-border" strokeWidth="1" d="M 0 10 L 10 0 L 20 10" fill="none" />
      </svg> }
    </div>
  </div>;
}

// ParcelWs/libs/trmrk-angular/projects/trmrk-angular/src/lib/components/common/trmrk-user-message/trmrk-user-message.ts
import {
  Component,
  Output,
  Input,
  EventEmitter,
  OnDestroy,
  OnChanges,
  SimpleChanges,
  ViewEncapsulation,
  ElementRef,
} from '@angular/core';

import { CommonModule } from '@angular/common';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';

import { defaultSlowAnimationDurationMillis } from '../../../../trmrk-browser/core';

import { whenChanged } from '../../../services/common/simpleChanges';
import { UserMessageLevel, NullOrUndef } from '../../../../trmrk/core';

import { Placement } from '../../../services/common/types';

@Component({
  selector: 'trmrk-user-message',
  imports: [CommonModule, MatIconModule, MatButtonModule],
  templateUrl: './trmrk-user-message.html',
  styleUrl: './trmrk-user-message.scss',
  encapsulation: ViewEncapsulation.None,
})
export class TrmrkUserMessage implements OnDestroy, OnChanges {
  @Output() trmrkClose = new EventEmitter<boolean>();
  @Input() trmrkAutoCloseMillis = 5000;
  @Input() trmrkShow = 0;
  @Input() trmrkMessage!: string;
  @Input() trmrkLevel!: UserMessageLevel;
  @Input() trmrkArrowPlacement = Placement.None;
  @Input() trmrkArrowStyle:
    | {
        [klass: string]: any;
      }
    | NullOrUndef = null;

  messageFadeOut = false;
  show = false;

  private timeouts: NodeJS.Timeout[] = [];

  constructor(public hostEl: ElementRef) {}

  get msgLevelCssClass() {
    let cssClass: string;

    switch (this.trmrkLevel) {
      case UserMessageLevel.Success:
        cssClass = 'trmrk-success';
        break;
      case UserMessageLevel.Info:
        cssClass = 'trmrk-info';
        break;
      case UserMessageLevel.Warn:
        cssClass = 'trmrk-warn';
        break;
      case UserMessageLevel.Error:
        cssClass = 'trmrk-error';
        break;
      default:
        throw new Error(`Invalid user message level: ${this.trmrkLevel}`);
    }

    return cssClass;
  }

  get arrowCssClass() {
    let cssClass: string;

    switch (this.trmrkArrowPlacement) {
      case Placement.None:
        cssClass = '';
        break;
      case Placement.Top:
        cssClass = 'trmrk-placement-top';
        break;
      case Placement.Right:
        cssClass = 'trmrk-placement-right';
        break;
      case Placement.Bottom:
        cssClass = 'trmrk-placement-bottom';
        break;
      case Placement.Left:
        cssClass = 'trmrk-placement-left';
        break;
      default:
        cssClass = '';
        break;
    }

    return cssClass;
  }

  ngOnChanges(changes: SimpleChanges): void {
    whenChanged(
      changes,
      () => this.trmrkShow,
      (value) => {
        this.show = value > 0;

        if (this.show && this.trmrkAutoCloseMillis > 0) {
          this.setFadeTimeouts();
        } else {
          this.clearTimeouts();
        }
      }
    );
  }

  ngOnDestroy(): void {
    this.clearTimeouts();
  }

  closeButtonClick() {
    this.show = false;
    this.trmrkClose.emit(true);
  }

  setFadeTimeouts() {
    this.timeouts.push(
      setTimeout(() => {
        this.messageFadeOut = true;

        this.timeouts.push(
          setTimeout(() => {
            this.messageFadeOut = false;
            this.show = false;
            this.trmrkClose.emit(false);
          }, defaultSlowAnimationDurationMillis)
        );
      }, this.trmrkAutoCloseMillis)
    );
  }

  clearTimeouts() {
    for (let tmt of this.timeouts) {
      clearTimeout(tmt);
    }

    this.timeouts.splice(0, this.timeouts.length);
  }
}
